// Code generated by MockGen. DO NOT EDIT.
// Source: task_service.go
//
// Generated by this command:
//
//	mockgen -source=task_service.go -destination=../mocks/mock_taskservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	task "github.com/Yash-Watchguard/Tasknest/internal/model/task"
	status "github.com/Yash-Watchguard/Tasknest/internal/model/task_status"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskServiceInterface is a mock of TaskServiceInterface interface.
type MockTaskServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskServiceInterfaceMockRecorder is the mock recorder for MockTaskServiceInterface.
type MockTaskServiceInterfaceMockRecorder struct {
	mock *MockTaskServiceInterface
}

// NewMockTaskServiceInterface creates a new mock instance.
func NewMockTaskServiceInterface(ctrl *gomock.Controller) *MockTaskServiceInterface {
	mock := &MockTaskServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTaskServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskServiceInterface) EXPECT() *MockTaskServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskServiceInterface) CreateTask(arg0 task.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceInterfaceMockRecorder) CreateTask(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).CreateTask), arg0)
}

// DeleteTask mocks base method.
func (m *MockTaskServiceInterface) DeleteTask(managerId, taskId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", managerId, taskId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskServiceInterfaceMockRecorder) DeleteTask(managerId, taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).DeleteTask), managerId, taskId)
}

// GetAssigenedTask mocks base method.
func (m *MockTaskServiceInterface) GetAssigenedTask(empId string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssigenedTask", empId)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssigenedTask indicates an expected call of GetAssigenedTask.
func (mr *MockTaskServiceInterfaceMockRecorder) GetAssigenedTask(empId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssigenedTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).GetAssigenedTask), empId)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskServiceInterface) UpdateTaskStatus(userId, taskId string, updatedStatus status.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", userId, taskId, updatedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskServiceInterfaceMockRecorder) UpdateTaskStatus(userId, taskId, updatedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskServiceInterface)(nil).UpdateTaskStatus), userId, taskId, updatedStatus)
}

// ViewAllAssignedTasksInProject mocks base method.
func (m *MockTaskServiceInterface) ViewAllAssignedTasksInProject(projectId, emp string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllAssignedTasksInProject", projectId, emp)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllAssignedTasksInProject indicates an expected call of ViewAllAssignedTasksInProject.
func (mr *MockTaskServiceInterfaceMockRecorder) ViewAllAssignedTasksInProject(projectId, emp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllAssignedTasksInProject", reflect.TypeOf((*MockTaskServiceInterface)(nil).ViewAllAssignedTasksInProject), projectId, emp)
}

// ViewAllTask mocks base method.
func (m *MockTaskServiceInterface) ViewAllTask(projectId string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllTask", projectId)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllTask indicates an expected call of ViewAllTask.
func (mr *MockTaskServiceInterfaceMockRecorder) ViewAllTask(projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).ViewAllTask), projectId)
}
