// Code generated by MockGen. DO NOT EDIT.
// Source: project.go
//
// Generated by this command:
//
//	mockgen -source=project.go -destination=../mocks/mock_projectrepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	project "github.com/Yash-Watchguard/Tasknest/internal/model/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// AddProject mocks base method.
func (m *MockProjectRepository) AddProject(newProject project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProject", newProject)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProject indicates an expected call of AddProject.
func (mr *MockProjectRepositoryMockRecorder) AddProject(newProject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProject", reflect.TypeOf((*MockProjectRepository)(nil).AddProject), newProject)
}

// DeleteProject mocks base method.
func (m *MockProjectRepository) DeleteProject(projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectRepositoryMockRecorder) DeleteProject(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectRepository)(nil).DeleteProject), projectID)
}

// ViewAllProjects mocks base method.
func (m *MockProjectRepository) ViewAllProjects() ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllProjects")
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllProjects indicates an expected call of ViewAllProjects.
func (mr *MockProjectRepositoryMockRecorder) ViewAllProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllProjects", reflect.TypeOf((*MockProjectRepository)(nil).ViewAllProjects))
}

// ViewAssignedProject mocks base method.
func (m *MockProjectRepository) ViewAssignedProject(userId string) ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAssignedProject", userId)
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAssignedProject indicates an expected call of ViewAssignedProject.
func (mr *MockProjectRepositoryMockRecorder) ViewAssignedProject(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAssignedProject", reflect.TypeOf((*MockProjectRepository)(nil).ViewAssignedProject), userId)
}
