// Code generated by MockGen. DO NOT EDIT.
// Source: comment_service.go
//
// Generated by this command:
//
//	mockgen -source=comment_service.go -destination=../mocks/mock_commentservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	comment "github.com/Yash-Watchguard/Tasknest/internal/model/comment"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentServiceInterface is a mock of CommentServiceInterface interface.
type MockCommentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCommentServiceInterfaceMockRecorder is the mock recorder for MockCommentServiceInterface.
type MockCommentServiceInterfaceMockRecorder struct {
	mock *MockCommentServiceInterface
}

// NewMockCommentServiceInterface creates a new mock instance.
func NewMockCommentServiceInterface(ctrl *gomock.Controller) *MockCommentServiceInterface {
	mock := &MockCommentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCommentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentServiceInterface) EXPECT() *MockCommentServiceInterfaceMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockCommentServiceInterface) AddComment(newComment comment.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", newComment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddComment indicates an expected call of AddComment.
func (mr *MockCommentServiceInterfaceMockRecorder) AddComment(newComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockCommentServiceInterface)(nil).AddComment), newComment)
}

// DeleteComment mocks base method.
func (m *MockCommentServiceInterface) DeleteComment(ctx context.Context, commentId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, commentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentServiceInterfaceMockRecorder) DeleteComment(ctx, commentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentServiceInterface)(nil).DeleteComment), ctx, commentId)
}

// UpdateComment mocks base method.
func (m *MockCommentServiceInterface) UpdateComment(ctx context.Context, updatedComment comment.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", ctx, updatedComment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentServiceInterfaceMockRecorder) UpdateComment(ctx, updatedComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentServiceInterface)(nil).UpdateComment), ctx, updatedComment)
}

// ViewAllComment mocks base method.
func (m *MockCommentServiceInterface) ViewAllComment(taskId string) ([]comment.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllComment", taskId)
	ret0, _ := ret[0].([]comment.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllComment indicates an expected call of ViewAllComment.
func (mr *MockCommentServiceInterfaceMockRecorder) ViewAllComment(taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllComment", reflect.TypeOf((*MockCommentServiceInterface)(nil).ViewAllComment), taskId)
}
