// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -source=task.go -destination=../mocks/mock_taskrepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	task "github.com/Yash-Watchguard/Tasknest/internal/model/task"
	status "github.com/Yash-Watchguard/Tasknest/internal/model/task_status"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
	isgomock struct{}
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockTaskRepo) DeleteTask(taskId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", taskId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskRepoMockRecorder) DeleteTask(taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskRepo)(nil).DeleteTask), taskId)
}

// SaveTask mocks base method.
func (m *MockTaskRepo) SaveTask(arg0 task.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTask", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTask indicates an expected call of SaveTask.
func (mr *MockTaskRepoMockRecorder) SaveTask(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTask", reflect.TypeOf((*MockTaskRepo)(nil).SaveTask), arg0)
}

// UpdateTask mocks base method.
func (m *MockTaskRepo) UpdateTask(taskId string, updatedfields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", taskId, updatedfields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskRepoMockRecorder) UpdateTask(taskId, updatedfields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskRepo)(nil).UpdateTask), taskId, updatedfields)
}

// UpdateTaskStatus mocks base method.
func (m *MockTaskRepo) UpdateTaskStatus(userId, empId string, updatedStatus status.TaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", userId, empId, updatedStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockTaskRepoMockRecorder) UpdateTaskStatus(userId, empId, updatedStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockTaskRepo)(nil).UpdateTaskStatus), userId, empId, updatedStatus)
}

// ViewAllAssignedTasksInProject mocks base method.
func (m *MockTaskRepo) ViewAllAssignedTasksInProject(projectId, empId string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllAssignedTasksInProject", projectId, empId)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllAssignedTasksInProject indicates an expected call of ViewAllAssignedTasksInProject.
func (mr *MockTaskRepoMockRecorder) ViewAllAssignedTasksInProject(projectId, empId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllAssignedTasksInProject", reflect.TypeOf((*MockTaskRepo)(nil).ViewAllAssignedTasksInProject), projectId, empId)
}

// ViewAllManagerTask mocks base method.
func (m *MockTaskRepo) ViewAllManagerTask(managerId string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllManagerTask", managerId)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllManagerTask indicates an expected call of ViewAllManagerTask.
func (mr *MockTaskRepoMockRecorder) ViewAllManagerTask(managerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllManagerTask", reflect.TypeOf((*MockTaskRepo)(nil).ViewAllManagerTask), managerId)
}

// ViewAllTask mocks base method.
func (m *MockTaskRepo) ViewAllTask(projectId string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllTask", projectId)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllTask indicates an expected call of ViewAllTask.
func (mr *MockTaskRepoMockRecorder) ViewAllTask(projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllTask", reflect.TypeOf((*MockTaskRepo)(nil).ViewAllTask), projectId)
}

// ViewAssignedTask mocks base method.
func (m *MockTaskRepo) ViewAssignedTask(empId string) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAssignedTask", empId)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAssignedTask indicates an expected call of ViewAssignedTask.
func (mr *MockTaskRepoMockRecorder) ViewAssignedTask(empId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAssignedTask", reflect.TypeOf((*MockTaskRepo)(nil).ViewAssignedTask), empId)
}
