// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go
//
// Generated by this command:
//
//	mockgen -source=user_service.go -destination=../mocks/mock_userservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user "github.com/Yash-Watchguard/Tasknest/internal/model/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// CheckUserExist mocks base method.
func (m *MockUserServiceInterface) CheckUserExist(email string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExist", email)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckUserExist indicates an expected call of CheckUserExist.
func (mr *MockUserServiceInterfaceMockRecorder) CheckUserExist(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExist", reflect.TypeOf((*MockUserServiceInterface)(nil).CheckUserExist), email)
}

// DeleteUser mocks base method.
func (m *MockUserServiceInterface) DeleteUser(userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceInterfaceMockRecorder) DeleteUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServiceInterface)(nil).DeleteUser), userId)
}

// GetAllManager mocks base method.
func (m *MockUserServiceInterface) GetAllManager(ctx context.Context) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllManager", ctx)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllManager indicates an expected call of GetAllManager.
func (mr *MockUserServiceInterfaceMockRecorder) GetAllManager(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllManager", reflect.TypeOf((*MockUserServiceInterface)(nil).GetAllManager), ctx)
}

// IsUserPresent mocks base method.
func (m *MockUserServiceInterface) IsUserPresent(name, email, password string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserPresent", name, email, password)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserPresent indicates an expected call of IsUserPresent.
func (mr *MockUserServiceInterfaceMockRecorder) IsUserPresent(name, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserPresent", reflect.TypeOf((*MockUserServiceInterface)(nil).IsUserPresent), name, email, password)
}

// PromoteEmployee mocks base method.
func (m *MockUserServiceInterface) PromoteEmployee(employeeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteEmployee", employeeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PromoteEmployee indicates an expected call of PromoteEmployee.
func (mr *MockUserServiceInterfaceMockRecorder) PromoteEmployee(employeeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteEmployee", reflect.TypeOf((*MockUserServiceInterface)(nil).PromoteEmployee), employeeId)
}

// UpdateUser mocks base method.
func (m *MockUserServiceInterface) UpdateUser(id string, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateUser(id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateUser), id, updates)
}

// ViewAllEmplpyee mocks base method.
func (m *MockUserServiceInterface) ViewAllEmplpyee(ctx context.Context) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllEmplpyee", ctx)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllEmplpyee indicates an expected call of ViewAllEmplpyee.
func (mr *MockUserServiceInterfaceMockRecorder) ViewAllEmplpyee(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllEmplpyee", reflect.TypeOf((*MockUserServiceInterface)(nil).ViewAllEmplpyee), ctx)
}

// ViewAllUsers mocks base method.
func (m *MockUserServiceInterface) ViewAllUsers() ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllUsers")
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllUsers indicates an expected call of ViewAllUsers.
func (mr *MockUserServiceInterfaceMockRecorder) ViewAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllUsers", reflect.TypeOf((*MockUserServiceInterface)(nil).ViewAllUsers))
}

// ViewProfile mocks base method.
func (m *MockUserServiceInterface) ViewProfile(userId string) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewProfile", userId)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewProfile indicates an expected call of ViewProfile.
func (mr *MockUserServiceInterfaceMockRecorder) ViewProfile(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).ViewProfile), userId)
}
