// Code generated by MockGen. DO NOT EDIT.
// Source: project_service.go
//
// Generated by this command:
//
//	mockgen -source=project_service.go -destination=../mocks/mock_projectservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	project "github.com/Yash-Watchguard/Tasknest/internal/model/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectServiceInterface is a mock of ProjectServiceInterface interface.
type MockProjectServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockProjectServiceInterfaceMockRecorder is the mock recorder for MockProjectServiceInterface.
type MockProjectServiceInterfaceMockRecorder struct {
	mock *MockProjectServiceInterface
}

// NewMockProjectServiceInterface creates a new mock instance.
func NewMockProjectServiceInterface(ctrl *gomock.Controller) *MockProjectServiceInterface {
	mock := &MockProjectServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProjectServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectServiceInterface) EXPECT() *MockProjectServiceInterfaceMockRecorder {
	return m.recorder
}

// AddProject mocks base method.
func (m *MockProjectServiceInterface) AddProject(arg0 project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProject", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProject indicates an expected call of AddProject.
func (mr *MockProjectServiceInterfaceMockRecorder) AddProject(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProject", reflect.TypeOf((*MockProjectServiceInterface)(nil).AddProject), arg0)
}

// DeleteProject mocks base method.
func (m *MockProjectServiceInterface) DeleteProject(projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectServiceInterfaceMockRecorder) DeleteProject(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectServiceInterface)(nil).DeleteProject), projectID)
}

// ViewAllProjects mocks base method.
func (m *MockProjectServiceInterface) ViewAllProjects() ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllProjects")
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllProjects indicates an expected call of ViewAllProjects.
func (mr *MockProjectServiceInterfaceMockRecorder) ViewAllProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllProjects", reflect.TypeOf((*MockProjectServiceInterface)(nil).ViewAllProjects))
}

// ViewAssignedProject mocks base method.
func (m *MockProjectServiceInterface) ViewAssignedProject(userId string) ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAssignedProject", userId)
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAssignedProject indicates an expected call of ViewAssignedProject.
func (mr *MockProjectServiceInterfaceMockRecorder) ViewAssignedProject(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAssignedProject", reflect.TypeOf((*MockProjectServiceInterface)(nil).ViewAssignedProject), userId)
}
