// Code generated by MockGen. DO NOT EDIT.
// Source: comment.go
//
// Generated by this command:
//
//	mockgen -source=comment.go -destination=../mocks/mock_commentrepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	comment "github.com/Yash-Watchguard/Tasknest/internal/model/comment"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentRepo is a mock of CommentRepo interface.
type MockCommentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommentRepoMockRecorder
	isgomock struct{}
}

// MockCommentRepoMockRecorder is the mock recorder for MockCommentRepo.
type MockCommentRepoMockRecorder struct {
	mock *MockCommentRepo
}

// NewMockCommentRepo creates a new mock instance.
func NewMockCommentRepo(ctrl *gomock.Controller) *MockCommentRepo {
	mock := &MockCommentRepo{ctrl: ctrl}
	mock.recorder = &MockCommentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentRepo) EXPECT() *MockCommentRepoMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockCommentRepo) AddComment(newComment comment.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", newComment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddComment indicates an expected call of AddComment.
func (mr *MockCommentRepoMockRecorder) AddComment(newComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockCommentRepo)(nil).AddComment), newComment)
}

// DeleteComment mocks base method.
func (m *MockCommentRepo) DeleteComment(userId, commentId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", userId, commentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentRepoMockRecorder) DeleteComment(userId, commentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentRepo)(nil).DeleteComment), userId, commentId)
}

// UpdateComment mocks base method.
func (m *MockCommentRepo) UpdateComment(updatedComment comment.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", updatedComment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentRepoMockRecorder) UpdateComment(updatedComment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentRepo)(nil).UpdateComment), updatedComment)
}

// ViewAllComments mocks base method.
func (m *MockCommentRepo) ViewAllComments(projectId string) ([]comment.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllComments", projectId)
	ret0, _ := ret[0].([]comment.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllComments indicates an expected call of ViewAllComments.
func (mr *MockCommentRepoMockRecorder) ViewAllComments(projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllComments", reflect.TypeOf((*MockCommentRepo)(nil).ViewAllComments), projectId)
}
