Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Architectures:
      - x86_64
    Timeout: 200
    Handler: bootstrap
    Runtime: provided.al2023

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v5
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  Login:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/auth/login
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /login
            RestApiId: !Ref Api

  Signup:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/auth/signup
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /signup
            RestApiId: !Ref Api

  AddComment:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: AddComment
    Properties:
      CodeUri: ./cmd/comment/addcomment
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /projects/{project_id}/tasks/{task_id}/comments
            RestApiId: !Ref Api

  ViewAllComment:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewAllComment
    Properties:
      CodeUri: ./cmd/comment/viewallcomment
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /projects/{project_id}/tasks/{task_id}/comments
            RestApiId: !Ref Api

  AddTask:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: AddTask
    Properties:
      CodeUri: ./cmd/task/addtask
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskNest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /projects/{project_id}/tasks
            RestApiId: !Ref Api

  UpdateTask:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: updateTask
    Properties:
      CodeUri: ./cmd/task/updatetask
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskNest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /projects/{project_id}/tasks/{task_id}/manager/{manager_id}/update
            RestApiId: !Ref Api

  DeleteTask:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: DeleteTask
    Properties:
      CodeUri: ./cmd/task/deletetask
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /projects/{project_id}/tasks/{task_id}/manager/{manager_id}/employee/{emp_id}/deletetask
            RestApiId: !Ref Api

  GetAssignedEmpTask:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetAssignedEmpTask
    Properties:
      CodeUri: ./cmd/task/getassignedtask
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskNest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /employees/{emp_id}/tasksy
            RestApiId: !Ref Api

  GetAllProjectTask:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetAllProjectTask
    Properties:
      CodeUri: ./cmd/task/getprojecttask
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskNest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /creator/{creator_id}/projects/{project_id}
            RestApiId: !Ref Api

  PromoteEmployee:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: PromoteEmployee
    Properties:
      CodeUri: ./cmd/user/promoteemp
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskNest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /users/promote/{user_email}
            RestApiId: !Ref Api

  DeleteProject:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: DeleteProject
    Properties:
      CodeUri: ./cmd/project/deleteproject
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskNest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /project/{project_id}/assigned/{manager_id}/delete
            RestApiId: !Ref Api

  ViewAllManagerTask:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewAllManagerTask
    Properties:
      CodeUri: ./cmd/task/getallmangerTask
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /projects/managers/{manager_id}/tasks
            RestApiId: !Ref Api

  GetProjectStatus:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetProjectStatus
    Properties:
      CodeUri: ./cmd/project/getprojectstatus
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /projects/{project_id}/status/creator/{creator_id}
            RestApiId: !Ref Api

  